// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhZECLs_G-6BKPK1BH0BSKFHQTJG8vbqk',
    appId: '1:1095039866407:web:20d4eaf9e302df0c55e002',
    messagingSenderId: '1095039866407',
    projectId: 'projet-certif',
    authDomain: 'projet-certif.firebaseapp.com',
    storageBucket: 'projet-certif.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjzjk0kot7uj-QZcwivbIAkXDRX-DRVfA',
    appId: '1:1095039866407:android:033b5f1898d61ec255e002',
    messagingSenderId: '1095039866407',
    projectId: 'projet-certif',
    storageBucket: 'projet-certif.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3tJ4MWnphEEZit7YGJWFVB4vtA4EZ2Gc',
    appId: '1:1095039866407:ios:4169d835eb50239755e002',
    messagingSenderId: '1095039866407',
    projectId: 'projet-certif',
    storageBucket: 'projet-certif.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3tJ4MWnphEEZit7YGJWFVB4vtA4EZ2Gc',
    appId: '1:1095039866407:ios:4169d835eb50239755e002',
    messagingSenderId: '1095039866407',
    projectId: 'projet-certif',
    storageBucket: 'projet-certif.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhZECLs_G-6BKPK1BH0BSKFHQTJG8vbqk',
    appId: '1:1095039866407:web:885646448649828855e002',
    messagingSenderId: '1095039866407',
    projectId: 'projet-certif',
    authDomain: 'projet-certif.firebaseapp.com',
    storageBucket: 'projet-certif.appspot.com',
  );
}
